# PreProcessing

In [449]:
import csv
import numpy as np
import pandas as pd
import math

In [450]:
df_SM = pd.read_csv(r"C:\Users\Clamfighter\Documents\00-Work\Heggle\B2B ML Model\Data\Tritech\StanfordMarsh.csv",encoding = "ISO-8859-1" )

In [451]:
df_SM = df_SM[df_SM['TurnoverY0'].notna()]
df_SM

,Name,TurnoverY0,TurnoverY1,AssetsY0,AssetsY1,AdminCostsY0,AdminCostsY1,Employee#Y0,Employee#Y1,StaffCostsY0,StaffCostsY1,Distribution costsY0,Distribution costsY1
3,3D Print N Scan,"25,496",NaN,"23,894","18,408",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,A Edmonds & Co Limited,5585901,6570211,2333601,2108780,NaN,NaN,83,87,NaN,NaN,NaN,NaN
7,A Poole & Son Ltd,5663578,6509953,17988703,16801486,1196805,1019332,88,85,3036639,2856370,60200,57308
12,A.N. Wallis & Co Ltd,26561428,30419178,12616309,11469004,4448844,2813988,86,87,3636139,3472915,584429,1669377
14,AAK (UK) Ltd,255225,262778,33207,38124,8687,8034,430,407,18835,17099,10262,9783
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1050,SPP Pumps Ltd,101143476,77188511,15438778,13996861,11479138,11474532,433,427,19661384,20406292,7322008,8301033
1051,Sprue Safety Products,43800000,36000000,13007000,3579000,9191000,8529000,124,125,NaN,NaN,920000,992000
1053,SS Tube Technology Ltd,8272027,7719088,4034697,3244833,2789447,2569223,100,95,3639123,3345864,3639123,3345864
1056,Stanley Black & Decker UK Limited,304502000,288070000,17799000,11466000,5996000,6652000,408,371,18055000,165858000,28807000,27661000
1057,Star Ceilings South West Ltd,"652,808","625,498","60,895","36,585","314,399","338,079",NaN,NaN,"247,818","279,876","47,816","23,985"

In [452]:
df_CD = pd.read_csv(r"C:\Users\Clamfighter\Machine_Learning_Project\my_env\Heggle\B2B Customer Identification\Data\CompanyData_Filtered_CH.csv",encoding = "ISO-8859-1" ) 
df_CD = df_CD[df_CD['Name'].notna()]
df_CD = df_CD[df_CD['TurnoverY1'].notna()]
df_CD = df_CD[df_CD['StaffCostsY0'].notna()]
df_CD = df_CD[df_CD3['AdminCostsY0'].notna()]
df_CD = df_CD.sample(n = 399)
df_CD

,Name,TurnoverY0,TurnoverY1,AssetsY0,AssetsY1,AdminCostsY0,AdminCostsY1,Employee#Y0,Employee#Y1,StaffCostsY0,StaffCostsY1,Distribution costsY1
1666,ASHTON LODGE LIMITED,"5,343,431","5,053,004","2,508,947",NaN,"4,800,664","4,314,211","47,665","87,267","2,959,141","2,542,898",NaN
2087,FIDELITI LIMITED,"83,729,421","86,938,453","1,099,400",NaN,"737,368","830,278","332,968","281,571","568,314","630,730",NaN
1810,SPI PILING LIMITED,"10,647,202","11,485,389","4,129,420",NaN,"1,201,954","1,172,361",NaN,"2,702","2,300,017","2,484,380",NaN
1737,ROFFEY HOMES LIMITED,"7,961,491","7,955,089","16,988,390",NaN,"977,338","797,006","30,840","317,496","650,398","650,398",NaN
2007,Dundas Chemical Company (Mosspark) Limited,"27,311,973","26,990,343","25,469,044",NaN,"2,103,198","2,141,842","301,535","42,713","6,447,448","6,622,648",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1518,CF PARTNERS SERVICES (UK) LIMITED,"1,942,281","1,714,854","1,919,986",NaN,"2,016,775","1,565,600","6,415","48,515","1,181,705","1,074,602",NaN
1835,EUGENE HARRINGTON MARKETING LIMITED,"14,850,692","12,880,059","4,597,294",NaN,"2,929,212","2,538,854","188,873","142,070","1,999,655","1,687,352",NaN
2053,CRAIG INTERNATIONAL LIMITED,"41,376,742","40,797,451","4,449,087",NaN,"2,801,468","2,889,285",NaN,NaN,"1,818,224","1,942,642",NaN
1768,JAMES ALPE LIMITED,"10,520,175","9,156,383","2,574,884",NaN,"1,545,671","1,458,455","72,539","76,813","3,474,846","3,269,906",NaN
2074,THE HALCYON GALLERY LIMITED,"66,388,756","69,026,246","19,398,668",NaN,"18,511,763","15,000,683","757,369","766,136","8,312,294","6,562,001",NaN

In [453]:
df_SM["Label"] = 1
df_CD["Label"] = 0

In [454]:
df_SM = pd.concat([df_SM,df_CD])

In [455]:
df_SM = df_SM.reset_index(drop=True)
df_SM

,Name,TurnoverY0,TurnoverY1,AssetsY0,AssetsY1,AdminCostsY0,AdminCostsY1,Employee#Y0,Employee#Y1,StaffCostsY0,StaffCostsY1,Distribution costsY0,Distribution costsY1,Label
0,3D Print N Scan,"25,496",NaN,"23,894","18,408",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,A Edmonds & Co Limited,5585901,6570211,2333601,2108780,NaN,NaN,83,87,NaN,NaN,NaN,NaN,1
2,A Poole & Son Ltd,5663578,6509953,17988703,16801486,1196805,1019332,88,85,3036639,2856370,60200,57308,1
3,A.N. Wallis & Co Ltd,26561428,30419178,12616309,11469004,4448844,2813988,86,87,3636139,3472915,584429,1669377,1
4,AAK (UK) Ltd,255225,262778,33207,38124,8687,8034,430,407,18835,17099,10262,9783,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
793,CF PARTNERS SERVICES (UK) LIMITED,"1,942,281","1,714,854","1,919,986",NaN,"2,016,775","1,565,600","6,415","48,515","1,181,705","1,074,602",NaN,NaN,0
794,EUGENE HARRINGTON MARKETING LIMITED,"14,850,692","12,880,059","4,597,294",NaN,"2,929,212","2,538,854","188,873","142,070","1,999,655","1,687,352",NaN,NaN,0
795,CRAIG INTERNATIONAL LIMITED,"41,376,742","40,797,451","4,449,087",NaN,"2,801,468","2,889,285",NaN,NaN,"1,818,224","1,942,642",NaN,NaN,0
796,JAMES ALPE LIMITED,"10,520,175","9,156,383","2,574,884",NaN,"1,545,671","1,458,455","72,539","76,813","3,474,846","3,269,906",NaN,NaN,0
797,THE HALCYON GALLERY LIMITED,"66,388,756","69,026,246","19,398,668",NaN,"18,511,763","15,000,683","757,369","766,136","8,312,294","6,562,001",NaN,NaN,0

## Turnover / Assets

In [456]:
print(df_SM.index)

RangeIndex(start=0, stop=798, step=1)

In [457]:
#If there's no data for y1 turnover, replaces it with y0 turnover
for i in df_SM.index:
    if  pd.isna(df_SM['TurnoverY1'].loc[i]) == True:
        df_SM['TurnoverY1'].loc[i] = df_SM['TurnoverY0'].loc[i]

c:\users\clamfighter\machine_learning_project\my_env\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [458]:
#If there's no data for y1 Assets, replaces it with y0 Assets
count = 0
for i in df_SM.index:
    if (pd.isna(df_SM['AssetsY0'].loc[i]) == False) and (pd.isna(df_SM['AssetsY1'].loc[i]) == True):
        df_SM['AssetsY1'].loc[i] = df_SM['AssetsY0'].loc[i]
        count +=1
print("Number Changed: ",count)
df_SM

Number Changed:  380

,Name,TurnoverY0,TurnoverY1,AssetsY0,AssetsY1,AdminCostsY0,AdminCostsY1,Employee#Y0,Employee#Y1,StaffCostsY0,StaffCostsY1,Distribution costsY0,Distribution costsY1,Label
0,3D Print N Scan,"25,496","25,496","23,894","18,408",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,A Edmonds & Co Limited,5585901,6570211,2333601,2108780,NaN,NaN,83,87,NaN,NaN,NaN,NaN,1
2,A Poole & Son Ltd,5663578,6509953,17988703,16801486,1196805,1019332,88,85,3036639,2856370,60200,57308,1
3,A.N. Wallis & Co Ltd,26561428,30419178,12616309,11469004,4448844,2813988,86,87,3636139,3472915,584429,1669377,1
4,AAK (UK) Ltd,255225,262778,33207,38124,8687,8034,430,407,18835,17099,10262,9783,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
793,CF PARTNERS SERVICES (UK) LIMITED,"1,942,281","1,714,854","1,919,986","1,919,986","2,016,775","1,565,600","6,415","48,515","1,181,705","1,074,602",NaN,NaN,0
794,EUGENE HARRINGTON MARKETING LIMITED,"14,850,692","12,880,059","4,597,294","4,597,294","2,929,212","2,538,854","188,873","142,070","1,999,655","1,687,352",NaN,NaN,0
795,CRAIG INTERNATIONAL LIMITED,"41,376,742","40,797,451","4,449,087","4,449,087","2,801,468","2,889,285",NaN,NaN,"1,818,224","1,942,642",NaN,NaN,0
796,JAMES ALPE LIMITED,"10,520,175","9,156,383","2,574,884","2,574,884","1,545,671","1,458,455","72,539","76,813","3,474,846","3,269,906",NaN,NaN,0
797,THE HALCYON GALLERY LIMITED,"66,388,756","69,026,246","19,398,668","19,398,668","18,511,763","15,000,683","757,369","766,136","8,312,294","6,562,001",NaN,NaN,0

In [459]:
for i in df_SM.index:
     if (pd.isna(df_SM['TurnoverY0'].loc[i]) == False):
            print(
            (df_SM['TurnoverY0'].loc[i])  
            )

25,496
5585901
5663578
26561428
255225
13719000
70900000
18888645
13500000
8899215
9622162
15235935
10571247
4390572
1842993
20089000
34118000
59,165
1827000
5525000000
50438000
21700000
58232000
11907497
18744000
113373000
43,002,439
8,593,740
34645000
50577000
22,276,145
184145000
99388000
8476178
29654000
8136302
1637000
25700000
92310000
579400000
949497000
76681393
28002455
26852000
12588714
121066796
142069830
1142757219
65423144
16,464,503
212589000
1375336000
205884000
69120000
8005981
15404757
337384000
9545751
27550864
13783808
104495400
33685000
67737000000
36680231
2247531
25458710
141344434
30594099
19,486,383
30045911
53341893
4254209
362931000
42476038
51397000
42476038
51397000
9915041
32786448
8530010
8008362
10100032
456700000
87130590
17875430
10048000
6,611,019
32358031
60769233
431803000
26907577
26825000000
26035000
71686073
261973000
292684000
12989368000
7260000
621304
4568867
17707784
1829607
18129142
1703000
48416000
180478000
282664000
1344138000
121168000
121168000
2862911
606152000
98905000
10758782
23724000
18785257
14357000
152823061
7354722
12662392
3244000
5811000
30965000
6779425
8001000000
14208132
32285000
104141000
20043174
19556285
12929000
3497751
28612000
3904800000
12,433,672
53341893
1520335000
6654951
42205000
313288000
11289244
11110653
5753694
18777000
70043000
31500000
164000000
72188000
20888000
277901000
17,856,515
26441859
8995938
106510139
26,206,914
52118737
19093085
18164550
39195000
1960000
44403000
4,554,955
29097465
12909000000
9306767
6186956
517046523
57524398
20550000
12839000
90707000
5,320,957
9208441
15476468
208340000
352724000
4841700000
825520000
76289000
2362000
786000
16573290
22111000
8763107
17386000
8582478
761623000
33754000000
150964000
136102701
20237410
507595000
11172568
274930
34538000
3964978
77025350
84,366,793
10,288,456
12548708
29699176
10010865
36746026
5,479Â
37076000
2809899
41540000
12553737
17766332
55586767
89886000
25428046
2784296
11511018
43091000
20664000
36709520
18,108,780
14312000
29654000
156930000
54934999
10243018
4107684
1054813000
9395091
2604427000
11352330
43041000
142579000
15868000
28678000
20870000000
13972599
16879258
6142985
53127000
19,708,000
31546000
25123000
129133000
7,507,605
559056000
46572000
135800000
204787000
22947000
26566534
23122000
35001000
87064000
20417963
21505000
306374000
10922040
90724000
18596000
60836000
61989291
41820988
8700440
20082560
75253365
149116000
8738249
81949125
25386000
10,899,384
28299000
16320615
5390412
10557999
44526000
618950000
1835622
29634643
118017000
479319000
843040
8651463
17459095
11392394
13740061
2078258
28,395,920
5581261
1449268000
33729069
13570179
75375000
22909208
7123000
24542053
48225000
71099000
13420007
19198255
24256000
55707000
50009000
39270246
21997233
18803000
15,191,829
10235768
235151000
16294000
1653948000
20,227,030
189439000
303051000
14,921,050
51,460,690
59913837
16470153
107832000
1470572000
3409000
400400000
42552000
17903736
39807000
13041413
4233000000
28,995,717
7,773,617
20019798
29022842
12013446
357,228
13447000
551,415
12279000
18,959,550
289339000
19043000
1008609000
245438000
18822000
5377211
510215000
496418000
132420815
8263654
16197423
13386118
739486000
10028000
12,821,049
110096000
27951000
7734000000
266800000
730006000
274968000
24030000000
14915000
11957616
13887000
35847000
293463000
1128000000
2074000
1469000
692881000
646637000
1382600000
11846004
5412399
18273625
11591715
14985493
36437548
756014000
11805427
115496000
16551460
89561000
253994000
42950000
305019000
139319000
3434000
53944560
31244054
3657900000
100548000
21673270
77914101
27876000
173233000
24676000
7564907
135746000
101143476
43800000
8272027
304502000
652,808
5,343,431
83,729,421
10,647,202
7,961,491
27,311,973
72,780,829
17,711,991
8,876,957
21,845,866
21,989,456
12,949,716
7,458,447
17,068,691
294,826
10,999,959
29,366,890
15,601,039
3,914,176
47,409,403
13,089,705
4,782,024
21,800,431
28,330,493
52,234,421
1,003,927
3,862,579
14,601,410
1,260,356
23,326,402
31,377,527
14,251,117
26,210,486
12,460,388
29,295,473
1,314,624
33,590,279
59,012
2,493,539
9,400,471
31,182,039
14,787,469
6,962,468
24,785,550
53,209,902
21,474,983
16,172,936
12,950,773
15,468,643
7,636,302
58,038,508
17,962,367
21,891,758
21,522,604
5,862,950
27,270,509
7,197,258
9,025,864
16,055,581
2,498,983
8,043,376
16,551,141
10,605,342
9,107,309
16,303,996
3,912,047
16,719,898
2,684
27,513,895
10,371,770
14,085,262
11,338,531
3,751,681
35,045,013
14,383,973
38,211,111
28,372,946
126,004,913
28,606,284
41,842,043
46,068,218
19,051,162
9,608,363
32,238,499
5,731,885
20,190,609
15,727,017
34,239,226
11,628,475
1,074,665
18,425,093
34,740,148
40,456,341
7,865,240
23,454,934
41,940,562
53,441,627
25,793,635
75,355,354
7,955,309
8,773,441
33,927,342
14,581,602
33,538,360
4,661,862
16,259,486
623,930
27,360,938
22,492,397
11,874,457
4,818,333
12,602,884
1,492,648
540,811
11,556,774
14,504,324
58,618,058
31,154,918
17,603,606
1,216,665
6,929,339
153,235,357
750,477
1,222,000
12,679,667
324,545
18,242,327
3,938,938
32,405,678
16,074,321
14,078
78,890,090
6,062,247
13,382,342
12,428,407
24,970,681
9,238,041
8,555,416
12,356,314
11,259,711
31,517,519
5,904,809
30,612,506
15,832,964
122,046
5,674,552
14,622,747
703,921
19,013,455
67,253
30,195,508
17,729,102
47,613
15,196,436
14,196,542
29,258,271
1,583,105
319,068
14,819,361
28,897,767
61,044,294
77,201,568
13,331,659
113,440,220
25,893,908
15,543,867
97,094,278
26,395,985
88,753,736
14,653,923
41,324,482
2,899,246
925,251
14,861,323
6,188,415
17,977,682
15,830,550
24,170,143
20,722,219
12,222,318
29,775,453
32,720,482
6,135,775
23,125,055
21,879,650
2,338,896
14,652,186
2,003,700
28,355,422
17,715,075
7,645,264
71,871,705
8,367,128
13,594,279
20,387,388
9,170,231
3,905,133
5,039,143
21,205,166
23,893,088
12,456,956
56,308,681
74,702,485
16,341,963
150,401
13,905,849
468,042
5,434,891
62,422,678
5,095,885
30,233,286
88,837,337
22,100,160
30,772,962
27,088,317
409,363
16,372,436
36,643,643
6,099,692
15,846,515
4,328,833
6,273,380
11,174,379
87,455,291
5,006,025
12,251,928
303,046
7,836,892
12,309,508
20,654,378
26,377,754
15,626,534
226,808
18,107,360
21,693,864
19,819,726
7,539,773
22,373,679
5,751,434
6,999,692
37,781,025
345,906
80,586,919
10,329,365
7,605,965
1,000,549
7,944,533
162,009
16,397,417
17,575,777
14,338,304
12,838,648
35,788,496
10,594,298
47,141,277
13,630,725
1,162,370
15,371,160
10,724,513
4,373,986
24,680,434
3,487,664
1,788,148
16,718,506
37,080
24,546,991
14,655,906
8,635
4,356,736
24,085,605
17,428,762
15,134,084
73,072
16,945,820
5,926,477
4,711,302
10,945,704
14,192,815
11,687,524
328,745
22,858,887
10,430,913
20,590,772
12,587,266
454,903
1,711,821
17,513,430
23,856,083
3,942,890
29,473,466
3,288,844
75,539,443
12,499
52,728,475
7,524,193
2,951,723
11,205,670
11,411,993
1,262,710
6,840,524
15,080,326
3,392,915
5,016,553
95,569,507
2,245,436
13,053,921
15,381,562
146,782,341
22,034,177
55,462,365
99,036
10,066,937
46,431,016
19,879,167
2,797,180
318,275
12,665,858
51,518,701
46,770,476
37,433,001
2,225,144
21,383,840
21,516,733
14,980,451
1,491,199
50,869,240
23,492,201
6,045,786
16,842,280
10,283,436
7,081,651
15,421,064
35,784,683
57,701,332
56,143,903
13,893,527
8,763,071
20,032,271
18,848,371
21,450,958
37,795
15,518,937
18,022,286
3,263,007
554,916
18,504,792
27,576,929
18,329,214
470,145
4,247,777
1,139,216
82,005,719
23,149,025
1,117,795
3,008,019
2,476
9,202,222
13,135,659
3,056,516
7,274,804
9,281,685
892,528
9,677,511
55,873,415
7,189,079
10,415
64,341,733
15,213,701
112,119
26,753,417
15,793,098
50,008,059
665,626
8,848,493
204,665
18,108,780
255,714
3,124,236
6,090,658
35,510
3,264,562
70,516
14,912,797
7,693,448
6,402,189
41,431,174
22,334,813
30,697,814
85,525
45,242,695
10,891,590
57,610
71,022
14,545,352
14,323,444
1,942,281
14,850,692
41,376,742
10,520,175
66,388,756

In [460]:
# Removes the ',' from Turnover numbers & converts them into ints
for i in df_SM.index:
    if (pd.isna(df_SM['TurnoverY0'].loc[i]) == False):
        df_SM['TurnoverY0'].loc[i] = str(df_SM['TurnoverY0'].loc[i]).replace(",", "")
        df_SM['TurnoverY1'].loc[i] = str(df_SM['TurnoverY1'].loc[i]).replace(",", "") 
        df_SM['TurnoverY0'].loc[i] = int(df_SM['TurnoverY0'].loc[i])
        df_SM['TurnoverY1'].loc[i] = int(df_SM['TurnoverY1'].loc[i])

c:\users\clamfighter\machine_learning_project\my_env\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [461]:
# Removes the ',' from Turnover numbers & converts them into ints
for i in df_SM.index: 
    if (pd.isna(df_SM['AssetsY0'].loc[i]) == False):
        df_SM['AssetsY0'].loc[i] = str(df_SM['AssetsY0'].loc[i]).replace(",", "")
        df_SM['AssetsY1'].loc[i] = str(df_SM['AssetsY1'].loc[i]).replace(",", "") 

        df_SM['AssetsY0'].loc[i] = float(df_SM['AssetsY0'].loc[i])
        df_SM['AssetsY1'].loc[i] = float(df_SM['AssetsY1'].loc[i])

In [462]:
#Create new column for % change of turnover, calculates figure and appends the field
df_SM["Turnover%change"] = np.nan
for i in df_SM.index:
    if (pd.isna(df_SM['TurnoverY0'].loc[i]) == False):
        y0 = df_SM['TurnoverY0'].loc[i]
        y1 = df_SM['TurnoverY1'].loc[i]
        
        df_SM['Turnover%change'].loc[i] = (((y0-y1)/y1)*100)

## Employees

In [463]:
#If there's no data for y1 employees, replaces it with y0 employees
for i in df_SM.index:
    if (pd.isna(df_SM['Employee#Y0'].loc[i]) == False) and (pd.isna(df_SM['Employee#Y1'].loc[i]) == True):
        df_SM['Employee#Y1'].loc[i] = df_SM['Employee#Y0'].loc[i]

In [464]:
# Removes the ',' from Employee numbers & converts them into ints
for i in df_SM.index:
    if (pd.isna(df_SM['Employee#Y0'].loc[i]) == False):
        df_SM['Employee#Y0'].loc[i] = str(df_SM['Employee#Y0'].loc[i]).replace(",", "")
        df_SM['Employee#Y1'].loc[i] = str(df_SM['Employee#Y1'].loc[i]).replace(",", "") 
        df_SM['Employee#Y0'].loc[i] = int(df_SM['Employee#Y0'].loc[i])
        df_SM['Employee#Y1'].loc[i] = int(df_SM['Employee#Y1'].loc[i])

In [465]:
#If there's no data for y1 staffcosts, replaces it with y0 staffcosts
for i in df_SM.index:
    if (pd.isna(df_SM['StaffCostsY0'].loc[i]) == False) and (pd.isna(df_SM['StaffCostsY1'].loc[i]) == True):
        df_SM['StaffCostsY1'].loc[i] = df_SM['StaffCostsY0'].loc[i]

In [466]:
# Removes the ',' from Turnover numbers & converts them into ints
for i in df_SM.index:
    if (pd.isna(df_SM['StaffCostsY0'].loc[i]) == False):
        df_SM['StaffCostsY0'].loc[i] = str(df_SM['StaffCostsY0'].loc[i]).replace(",", "")
        df_SM['StaffCostsY1'].loc[i] = str(df_SM['StaffCostsY1'].loc[i]).replace(",", "") 
        df_SM['StaffCostsY0'].loc[i] = int(df_SM['StaffCostsY0'].loc[i])
        df_SM['StaffCostsY1'].loc[i] = int(df_SM['StaffCostsY1'].loc[i])

In [467]:
#Turnover per employee
#Create new column for % change of turnover, calculates figure and appends the field
df_SM["Turnover/Employee"] = np.nan
for i in df_SM.index:
    if (pd.isna(df_SM['TurnoverY0'].loc[i]) == False) and (pd.isna(df_SM['Employee#Y0'].loc[i]) == False):
        df_SM['Turnover/Employee'].loc[i] = ((df_SM['TurnoverY0'].iloc[i])/(df_SM['Employee#Y0'].iloc[i]))

In [468]:
#Staffcosts per employee
#Create new column for Staffcosts per employee, calculates figure and appends the field
df_SM["StaffCostsPerEmployee"] = np.nan
for i in df_SM.index:
    if (pd.isna(df_SM['StaffCostsY0'].loc[i]) == False) and (pd.isna(df_SM['Employee#Y0'].loc[i]) == False):
        print(df_SM['StaffCostsY0'].iloc[i])
        print(df_SM['Employee#Y0'].iloc[i])
        
        StaffCostsPerEmployee = ((df_SM['StaffCostsY0'].iloc[i])/(df_SM['Employee#Y0'].iloc[i]))
        print(StaffCostsPerEmployee)
        df_SM['StaffCostsPerEmployee'].loc[i] = (TurnoverPerEmployee)

3036639
88
34507.26136363636
3636139
86
42280.686046511626
18835
430
43.80232558139535
5189000
153
33915.032679738564
12962000
254
51031.496062992126
5242448
145
36154.81379310345
5880000
63
93333.33333333333
1557282
50
31145.64
4884429
95
51415.04210526316
3300292
85
38826.964705882354
1975837
29
68132.31034482758
10917000
303
36029.70297029703
516000000
8469
60928.090683669856
13570000
194
69948.45360824742
8740000
158
55316.45569620253
5439
116
46.88793103448276
5509000
188
29303.191489361703
26640000
539
49424.860853432285
6155719
177
34778.07344632768
3300721
80
41259.0125
11807
324
36.44135802469136
7074000
140
50528.57142857143
6693213
254
26351.232283464567
42306000
11026
3836.930890622166
15168000
412
36815.53398058253
1427436
21
67973.14285714286
6094000
146
41739.72602739726
2569905
58
44308.706896551725
6611681
201
32893.935323383084
128000000
2391
53534.08615641991
191252000
2173
88012.88541187298
9448190
179
52783.1843575419
4645627
135
34412.05185185185
3992000
77
51844.155844155845
4524606
168
26932.178571428572
73707477
572
128859.22552447552
12747370
457
27893.5886214442
175439452
6385
27476.813155833985
9855749
185
53274.31891891892
2673664
67
39905.432835820895
50072000
996
50273.09236947791
409381000
6916
59193.31983805668
24818000
78
318179.4871794872
11843000
292
40558.21917808219
1589846
30
52994.86666666667
4329162
121
35778.198347107435
65838000
1532
42975.195822454305
4783993
135
35436.985185185185
2290438
43
53266.0
24611000
487
50535.93429158111
13464000
216
62333.333333333336
9366652
237
39521.738396624474
4769217
77
61937.88311688312
5101453
159
32084.610062893084
23952586
711
33688.58790436006
8571274
205
41811.09268292683
6063393
232
26135.314655172413
7701678
231
33340.5974025974
9713336
263
36932.83650190114
1501169
38
39504.44736842105
89884000
1725
52106.666666666664
11207183
291
38512.65635738832
14145000
245
57734.69387755102
11207183
291
38512.65635738832
14145000
245
57734.69387755102
1897340
57
33286.666666666664
8241506
261
31576.65134099617
2491644
71
35093.57746478873
1763741
20
88187.05
2830785
106
26705.51886792453
62400000
1555
40128.61736334405
44788512
613
73064.45676998369
8585427
137
62667.3503649635
1993000
50
39860.0
3220397
103
31265.990291262136
394582
127
3106.9448818897636
11683069
253
46178.13833992095
8311552
231
35980.74458874459
1888000000
29147
64775.10549970838
7501507
118
63572.09322033898
20610000
285
72315.78947368421
195550000
1936
101007.23140495867
576164000
2960
194650.0
2743000
49
55979.5918367347
2106497
50
42129.94
1134230
39
29082.82051282051
2200365
61
36071.55737704918
3658000
26
140692.3076923077
12090000
298
40570.469798657716
38002000
699
54366.23748211731
39573000
135
293133.3333333333
317767000
21028
15111.613087312155
12057000
428
28170.560747663552
17057000
428
39852.80373831776
4783782
112
42712.33928571428
9172000
267
34352.059925093636
18165000
27
672777.7777777778
2048919
41
49973.634146341465
5336000
110
48509.09090909091
2733767
63
43393.12698412698
3767000
76
49565.78947368421
24194711
487
49681.13141683778
2124398
85
24992.917647058825
4335386
104
41686.403846153844
1840000
116
15862.068965517241
37162
437
85.03890160183066
3088432
52
59392.92307692308
3808
53
71.84905660377359
21012000
472
44516.94915254237
4547547
96
47370.28125
3338560
78
42802.05128205128
3125000
99
31565.656565656565
12379000
317
39050.473186119874
3108088
82
37903.51219512195
9713336
263
36932.83650190114
282279000
3773
74815.53140736814
2375086
62
38307.83870967742
9604000
211
45516.58767772512
58852000
1271
46303.697875688435
2414110
52
46425.192307692305
372077
16
23254.8125
2393176
68
35193.76470588235
3351000
71
47197.18309859155
12595000
362
34792.81767955801
57000000
2103
27104.13694721826
41900000
929
45102.26049515608
10754000
293
36703.07167235495
6118000
128
47796.875
64508000
1731
37266.32004621606
2397892
34
70526.23529411765
3994767
83
48129.72289156626
10443513
289
36136.723183391005
1599675
157
10189.012738853504
8125592
116
70048.20689655172
2839055
105
27038.619047619046
2830191
53
53399.83018867925
17952000
453
39629.13907284768
907000
15
60466.666666666664
12464000
227
54907.48898678414
5344924
191
27983.895287958116
952000000
8784
108378.87067395264
3185561
56
56885.017857142855
2454834
68
36100.5
68076988
2472
27539.234627831716
15124111
298
50752.05033557047
4711000
155
30393.548387096773
2405000
50
48100.0
25876000
440
58809.09090909091
1008282
27
37343.77777777778
5025416
87
57763.402298850575
2954677
75
39395.693333333336
87138000
3323
26222.690340054167
287039000
16377
17526.958539415034
54400000
576
94444.44444444444
204162000
2880
70889.58333333333
18966000
249
76168.67469879518
2775000
44
63068.181818181816
71477000
1022
69938.35616438356
5852479
153
38251.49673202614
2626000
70
37514.28571428572
1338388
36
37177.444444444445
2764419
78
35441.269230769234
28782000
620
46422.58064516129
39843645
986
40409.37626774848
5152865
134
38454.21641791045
88555000
1245
71128.5140562249
5515482
89
61971.70786516854
26337801
699
37679.257510729614
29038432
732
39669.98907103825
2850496
76
37506.52631578947
10767237
353
30502.087818696884
9318729
274
34009.959854014596
16239878
483
33622.93581780538
13034000
130
100261.53846153847
10295000
243
42366.25514403292
3882257
96
40440.177083333336
1301025
48
27104.6875
6674661
161
41457.52173913043
18950000
674
28115.72700296736
6277226
154
40761.207792207795
1415290
49
28883.469387755104
4395124
122
36025.60655737705
6500000
159
40880.50314465409
8046000
160
50287.5
6757756
182
37130.52747252747
4871143
152
32046.99342105263
6094000
146
41739.72602739726
21373000
546
39144.68864468864
9448000
218
43339.449541284404
1762452
38
46380.31578947369
704757
27
26102.11111111111
3844000
105
36609.52380952381
3393776
82
41387.51219512195
71256000
599
118958.26377295493
4705252
132
35645.84848484849
12923000
341
37897.360703812315
80682000
1760
45842.045454545456
2444
94
26.0
355247000
6101
58227.66759547615
2488000000
38199
65132.59509411241
4229784
113
37431.71681415929
4172109
143
29175.587412587414
3180353
61
52136.934426229505
30634000
305
100439.34426229508
2317000
66
35106.06060606061
8213000
171
48029.23976608187
12036000
52
231461.53846153847
58707000
964
60899.377593360994
3493761
98
35650.62244897959
126194
2971
42.475260854931
7874000
309
25482.200647249192
33935000
757
44828.26948480846
24257000
446
54387.892376681615
7334000
143
51286.71328671329
5259461
114
46135.62280701754
5026000
104
48326.92307692308
8295000
287
28902.439024390245
20504000
312
65717.94871794872
5996930
138
43456.014492753624
10608000
184
57652.17391304348
21958000
382
57481.67539267016
1736482
46
37749.608695652176
15174000
350
43354.28571428572
6755000
104
64951.92307692308
37095000
1256
29534.23566878981
16152916
507
31859.79487179487
5159833
172
29999.029069767443
6506316
153
42524.94117647059
3172022
91
34857.38461538462
50802000
793
64063.05170239596
2443057
45
54290.15555555555
31561095
1029
30671.61807580175
36522000
522
69965.5172413793
3202756
120
26689.633333333335
8599000
184
46733.69565217391
5446134
114
47773.10526315789
2457235
40
61430.875
3421048
93
36785.4623655914
10672000
270
39525.92592592593
118000
1623
72.70486752926679
8392697
183
45861.73224043716
8872000
254
34929.13385826772
38759000
606
63958.74587458746
3067251
71
43200.718309859156
3312094
79
41925.240506329115
4480419
69
64933.608695652176
3368520
52
64779.230769230766
9111029
195
46723.22564102564
113458000
2035
55753.31695331696
7653146
208
36793.971153846156
3156616
107
29501.084112149532
31293000
619
50554.11954765751
5269210
194
27160.876288659794
5350000
89
60112.3595505618
3251992
79
41164.45569620253
2099000
263
7980.988593155894
18816000
643
29262.830482115085
4293353
73
58813.05479452055
5329465
105
50756.80952380953
170
6287000
2.703992365198028e-05
11736000
534
21977.52808988764
13682000
224
61080.357142857145
10395376
230
45197.28695652174
3978777
118
33718.44915254237
8635000
238
36281.512605042015
4309575
121
35616.32231404959
5212106
115
45322.66086956522
20663000
447
46225.95078299776
4084000
142
28760.563380281692
545872000
7795
70028.47979474021
5276630
65
81178.92307692308
49277000
854
57701.40515222483
25501000
368
69296.19565217392
4958958
214
23172.70093457944
14553910
292
49842.15753424657
8551540
245
34904.244897959186
7450806
114
65357.94736842105
179706000
2483
72374.54691904954
1071000
27
39666.666666666664
99000000
2772
35714.28571428572
14859000
344
43194.767441860466
4706942
142
33147.47887323944
12277000
283
43381.62544169612
2055715
45
45682.555555555555
1816000000
24207
75019.622423266
10152847
285
35624.02456140351
2285860
70
32655.14285714286
6686586
208
32147.048076923078
7297460
105
69499.61904761905
1345389
34
39570.26470588235
4016000
81
49580.246913580246
185963
5
37192.6
5030000
71
70845.07042253521
4135850
97
42637.62886597938
33437000
434
77043.77880184332
13118000
187
70149.73262032085
10922000
59
185118.64406779662
5017000
215
23334.883720930233
897209
20
44860.45
109401000
2390
45774.4769874477
22689858
647
35069.33230293663
1457861
41
35557.58536585366
2720069
76
35790.38157894737
2481515
90
27572.38888888889
88943000
1332
66774.02402402402
4929000
77
64012.98701298701
3685797
71
51912.633802816905
25710000
387
66434.10852713179
8928000
194
46020.61855670103
5203000000
138683
37517.215520287275
60700000
1470
41292.51700680272
48149000
909
52969.19691969197
71528000
1784
40094.17040358744
2545000000
97400
26129.36344969199
6908000
150
46053.333333333336
1978251
40
49456.275
6030000
141
42765.95744680851
26250000
915
28688.524590163935
41071000
773
53131.953428201814
387000
201
1925.3731343283582
566000
5
113200.0
268940000
2203
122078.98320472083
138372000
2621
52793.590232735594
645800000
22864
28245.276417074878
2924370
87
33613.44827586207
1342701
25
53708.04
5637633
111
50789.48648648649
3116364
99
31478.424242424244
2183942
61
35802.32786885246
980985
26
37730.192307692305
240638000
3492
68911.22565864834
991802
70
14168.6
11655000
315
37000.0
3422502
90
38027.8
16582000
266
62338.34586466166
25534000
532
47996.240601503756
13426000
111
120954.95495495496
1022000
666
1534.5345345345345
5944000
132
45030.30303030303
1069000
27
39592.59259259259
11838883
293
40405.74402730376
14127931
252
56063.218253968254
304000000
2820
107801.41843971632
18881000
385
49041.55844155844
3270496
94
34792.51063829787
27740947
679
40855.59204712813
5424000
163
33276.073619631905
35810000
578
61955.01730103806
8739000
145
60268.96551724138
2702957
66
40953.893939393936
70661000
1153
61284.475281873376
19661384
433
45407.35334872979
3639123
100
36391.23
18055000
408
44252.450980392154
2959141
47665
62.08205181999371
568314
332968
1.7068126666826842
650398
30840
21.089429312581064
6447448
301535
21.38208831478933
9675031
318699
30.357895694683698
12285533
258908
47.4513456517373
2614472
85037
30.745110951703378
3994849
20724
192.76437946342406
2679611
75589
35.44974797920332
9074324
59452
152.63277938505013
2345851
179095
13.098361204947095
1128581
43383
26.014360463776132
6543333
357210
18.317888636936257
2260497
593830
3.806639947459711
1263638
31828
39.70208621339701
907957
68121
13.328591770525977
7941976
278334
28.533977164126554
3605982
155007
23.263349397124
2906042
815985
3.5613914471467
6367281
121857
52.252074152490216
192246
105853
1.8161601466184236
79135
7670
10.317470664928292
2253970
87775
25.678951865565367
2388647
157829
15.134398621292664
717544
14204
50.51703745423824
53992
891760
0.060545438234502556
6482286
175863
36.859862506610256
2748351
333284
8.246273448470374
3122311
241224
12.94361672138759
3168184
20443
154.97647116372352
4718720
91243
51.71596725228237
24744
59858
0.4133783287112834
2589993
1254654
2.0643085663457814
1184979
56976
20.797862257792755
3548903
253866
13.979434032127186
1778205
943466
1.8847579033054715
12169359
130264
93.42073788613892
1716598
23018
74.57633156660005
2463826
363142
6.784745361318713
11537038
3644894
3.1652602243028194
2288869
68503
33.41268265623403
4510480
124382
36.26312488945346
3003793
294620
10.195482316203924
3573847
274679
13.010994651939173
2199205
56438
38.96674226584925
3465969
62083
55.82798833819242
1863898
381947
4.879991202967951
3479785
567488
6.1319093972031125
3433082
90361
37.99296156527706
3030634
351520
8.621512289485663
3363840
200946
16.7400197067869
2937586
74543
39.40793904189528
4419800
168004
26.30770695935811
1718230
342867
5.011360090064077
613515
221765
2.766509593488603
1668828
153540
10.869011332551779
1587617
1291674
1.2291158605035017
1852165
252416
7.337748003296146
1953498
78409
24.91420627734061
701362
391460

1.7916568742655699
1659938
216444
7.669133817523239
1528347
247324
6.179533729035597
1642
265
6.19622641509434
1567534
82015
19.11277205389258
1907371
122259
15.601068224016228
2920986
159549
18.307767519696142
187434
65412
2.8654375343973584
2869554
2198
1305.5295723384895
16348285
603570
27.085980085159964
616497
40107
15.371306754431895
2388016
13636
175.1258433558228
1530900
65777
23.27409276798881
20354369
615206
33.08545267763969
3379934
573563
5.8928731455829615
11815547
307517
38.42241892318148
3288156
272246
12.077885441843039
8002025
315474
25.36508555380158
2046035
168638
12.132704372679942
3668314
384327
9.544773070848523
2246823
66407
33.834128932190886
8760978
365898
23.943771214928752
756071
76222
9.919327753142138
2901252
89082
32.568330302418
1676007
91333
18.350508578498463
330990
80272
4.123355590990632
1586537
178105
8.90787456837259
2568693
864
2973.0243055555557
4939615
270814
18.239880508393213
1370603
11568
118.48227869986168
806027
866181
0.9305526212188907
6327935
2950774
2.144500053206379
5329594
66488
80.15873541090122
3877670
614457
6.31072638117883
5431942
167744
32.38233260206028
4288826
130597
32.84015712458939
2036456
200400
10.16195608782435
1783387
70310
25.364628075664914
1768311
42547
41.56135567725104
1704008
695782
2.449054445214162
2659116
149078
17.837078576315754
203958
38063
5.358432073141897
1945446
201272
9.665755793155531
5030429
437816
11.48982449248086
3053008
83424
36.596279248177986
2912256
46293
62.90920873566198
3986744
73700
54.094219810040705
4154381
236430
17.571293829040307
2329586
89833
25.932407912459787
8191840
249947
32.774308153328505
725379
98647
7.353279876732186
10523504
63738
165.105651259845
3258292
57771
56.40013155389382
13895161
66198
209.90303332426961
548337
4634
118.32908933966335
1135378
20081
56.539913350928735
5249020
31518
166.54038961863063
828644
76781
10.792305388051732
13373889
290010
46.115268439019346
2040367
10726
190.22627260861458
3605499
179079
20.13356674987017
3838073
417694
9.188719493217523
1761
100
17.61
2177707
376510
5.7839287137127835
3440161
233575
14.728292839559028
2507276
130712
19.181681865475245
11422015
504
22662.728174603173
1254504
539551
2.325088823855391
1763529
12000
146.96075
1342486
15202
88.30982765425603
1865420
81754
22.81747682070602
2503940
52980
47.261985654964136
1521302
27677
54.966289699028074
3228904
153158
21.08217657582366
1820784
112127
16.23858660269159
1331795
257869
5.164618469067627
614314
46119
13.32019341269325
3423229
512969
6.673364277373486
1947785
196057
9.934789372478411
1018509
233082
4.369745411486086
22340
14
1595.7142857142858
767046
188978
4.058916910963181
3978502
9569
415.76988191033547
2927
255
11.47843137254902
1002625
124073
8.080928163258728
9651732
16224
594.9045857988166
1104307
653360
1.6901968287008693
793547
96142
8.253905681179921
286428
5119
55.95389724555577
14057520
94658
148.5085254283843
772127
177277
4.355483226814533
12621061
130120
96.99555026129727
9364344
918957
10.19018735370643
1048785
116108
9.03284011437627
1457766
298004
4.891766553469081
7809841
80813
96.64089936025144
3910917
1312460
2.979837099797327
840486
40298
20.856767085215147
5725958
496959
11.521992759966114
2336100
361182
6.467930295529677
8556521
53525
159.86027090144793
757294
2717
278.7243283032757
399677
8506
46.987655772395954
7085038
41579
170.39943240578177
2846946
65947
43.1702124433257
822804
250504
3.2845942579759204
2704909
201438
13.427997696561722
1695492
89344
18.977122134670488
3008459
138254
21.760375829994068
2158044
283076
7.623549859401716
869477
138387
6.282938426297267
9853596
111946
88.02097439837064
3168007
49599
63.872396620899615
3273122
227224
14.404825194521706
7743395
252274
30.694383884189413
3801069
128589
29.55983015654527
244655
710
344.5845070422535
4456249
85244
52.276394819576744
2939859
333332
8.819612278449114
1899146
19245
98.68256690049364
6013746
540047
11.13559745725835
1813979
67591
26.83758192658786
1639181
585315
2.800510836045548
5581872
239525
23.303922346310404
3709563
120402
30.809812129366623
2657639
50676
52.44374062672666
1541277
224531
6.864428519892576
3227573
190653
16.929043865032284
2815937
609347
4.62123716043568
609875
667570
0.9135746064083168
612528
702488
0.8719408730113539
7543882
437539
17.241621889705833
2919729
150394
19.413866244664018
51729
125642
0.41171741933429906
194934
11048
17.644279507603187
353573
47874
7.385491080753645
2225817
15093
147.47346451997615
7853731
342298
22.944133474341072
2232871
148765
15.00938392767116
4569491
177590
25.730564784053158
7444652
173366
42.941822502682186
9192065
233980
39.285686810838534
198472
43069
4.608233300053403
5861435
18116
323.55017663943477
4027651
10064
400.2037957074722
1875546
122462
15.315330469860038
6269564
43631
143.69517086475213
2413879
87921
27.455090365214225
3235847
144811
22.34531216551229
712413
108470
6.567834424264774
2362733
7342
321.8105420866249
2490111
126935
19.617213534486154
8734192
22623
386.07576360341244
2046201
94792
21.5862203561482
2918239
50265
58.05707748930667
2037768
371000
5.492636118598383
141970
130050
1.0916570549788542
7498531
378492
19.811597074706995
397496
49174
8.083458738357669
866544
28071
30.869723201880944
3482982
103713
33.582887391166004
635664
7029
90.43448570209134
2087746
104894
19.90338818235552
6725435
122577
54.86702236145443
2382008
233785
10.188882948007786
2647918
251427
10.531557867691218
8163093
1020079
8.002412558243037
2504214
100073
25.023872573021695
1617377
46810
34.55195471053194
773495
45550
16.981229418221734
2936724
93007
31.575300783811972
111170
422
263.436018957346
2694262
68239
39.48272981725992
1199582
104933
11.431885107640113
973761
87450
11.135060034305317
4138396
23895
173.19087675245868
4183251
627920
6.662076379156581
7343376
198023
37.08344990228408
3544495
1321614
2.6819441985330057
2238847
422354
5.300877936517708
541150
205606
2.631975720552902
1073057
182857
5.868285053347698
982852
62411
15.748057233500505
6255635
56820
110.09565293910595
2108570
46735
45.11757783245961
995614
234100
4.252943186672362
1484746
466084
3.18557599059397
516731
6143
84.11704378967931
5194255
175105
29.66365894748865
1563
469
3.3326226012793176
1262673
8566
147.40520663086622
390575
11987
32.583215149745556
3187290
3884
820.6204943357363
2917920
583562
5.000188497537537
45928
4710
9.751167728237792
1571495
74568
21.074656689196438
2430964
172413
14.09965605841787
2257497
102853
21.948771547742894
1766952
100398
17.599474093109425
1308565
26343
49.67410697338951
1610131
1321979
1.2179701795565587
1679374
188219
8.922446724294572
2493779
500414
4.983431718537052
252935
11635
21.739149119037386
502976
208867
2.408116169619902
3214620
238297
13.489972597221115
1600567
250414
6.391683372335413
2240170
72988
30.69230558447964
8549487
150596
56.7710098541794
41177060
63001
653.5937524801194
2575
10
257.5
13658330
802907
17.011098421112283
3989943
315799
12.63443836110944
358074
190438
1.880265493231393
5038659
162920
30.927197397495704
2857439
136919
20.869557913803053
1078273
13856
77.81993360277136
854513
504529
1.6936846048492753
6158078
12413
496.09908966406186
1174816
15243
77.07249229154365
755695
184024
4.106502412728775
22061704
641102
34.41215906361234
855679
58213
14.699105010908216
2446066
59520
41.09653897849462
2426428
76939
31.537035833582447
15992261
784267
20.391347589532646
2595123
44237
58.664082103216764
6653861
177815
37.42013328459354
25815
11395
2.2654673102237823
2560035
69263
36.96107589910919
14099706
126982
111.0370446204974
310691
26455
11.744131544131545
638221
83513
7.642175469687354
65953
2126
31.022107243650048
8094906
54688
148.01978496196605
1629514
147464
11.050249552433137
3173018
37476
84.66800085387982
6330816
354750
17.84585200845666
991463
73673
13.457616765979395
1845383
575303
3.207671435747771
5502083
97024
56.708474191952504
845130
58159
14.531370897023676
15965748
188681
84.61767745559966
11712330
2534
4622.07182320442
3302848
189962
17.386887903896568
3397624
1347
2522.363771343727
1259043
392458
3.208096152964139
4767372
320028
14.89673403577187
1043017
205709
5.0703518076506136
833156
42909
19.41681232375492
6216672
217443
28.589892523557896
2738751
37381
73.26585698616944
3084569
155990
19.77414577857555
755486
294207
2.567872280401214
3293180
20369
161.67607639059355
6513878
34756
187.41736678559099
7833
3631
2.1572569540071607
3908115
60280
64.83269741207697
1095773
367220
2.983968738086161
4852378
106038
45.76074614760746
5676653
141548
40.1040848334134
2918244
103172
28.285232427402782
202893
68707
2.9530178875514865
2130933
117441
18.144710961248627
62213272
1084836
57.348089480806316
4582346
178682
25.645258056211595
52790
482988
0.10929878175027123
816431
1247
654.7161186848437
325018
112294
2.894348763068374
957709
18214
52.580926759635446
123217
4967
24.807127038453796
1226644
710
1727.6676056338029
3656786
73585
49.69472039138412
41291
886
46.603837471783294
3733871
46597
80.1311457819173
12927164
387590
33.352676797647
2055451
43288
47.4831593051192
1303904
13775
94.657277676951
31482
3745
8.406408544726302
2370491
269024
8.811448049244676
1680934
174983
9.606270323402844
216767
495667
0.4373238484708484
702744
71891
9.775131796747855
2606861
95608
27.26613881683541
926986
129721
7.1459979494453485
4871143
373427
13.044431709544302
114467
17385
6.584239286741444
1585594
171555
9.242482002856226
2679
86
31.151162790697676
2355832
111833
21.06562463673513
36499
212
172.16509433962264
3879139
52353
74.09583022940424
1667340
2630
633.9695817490494
1811698
4772
379.651718357083
12763626
157107
81.24161240428498
1764274
811331
2.1745428191453304
1742073
1074151
1.6218138790542485
75130
1564
48.03708439897698
7751430
115331
67.21029038159732
3129628
43062
72.67725604941712
90076
12180
7.395402298850574
330641
16279
20.310891332391424
443889
413360
1.073855718985872
1181705
6415
184.20966484801247
1999655
188873
10.587299402243836
3474846
72539
47.90314175822661
8312294
757369
10.975223437980693

## AdminCosts

In [469]:
#If there's no data for y1 Admin, replaces it with y0 Admin
for i in df_SM.index:
    if (pd.isna(df_SM['AdminCostsY0'].loc[i]) == False) and (pd.isna(df_SM['AdminCostsY1'].loc[i]) == True):
        df_SM['AdminCostsY1'].loc[i] = df_SM['AdminCostsY0'].loc[i]

In [470]:
# Removes the ',' from Employee numbers & converts them into ints
for i in df_SM.index:
    if (pd.isna(df_SM['AdminCostsY0'].loc[i]) == False):
        df_SM['AdminCostsY0'].loc[i] = str(df_SM['AdminCostsY0'].loc[i]).replace(",", "")
        df_SM['AdminCostsY1'].loc[i] = str(df_SM['AdminCostsY1'].loc[i]).replace(",", "") 
        df_SM['AdminCostsY0'].loc[i] = int(df_SM['AdminCostsY0'].loc[i])
        df_SM['AdminCostsY1'].loc[i] = int(df_SM['AdminCostsY1'].loc[i])

In [471]:
#Turnover per employee
#Create new column for % change of turnover, calculates figure and appends the field
df_SM["TurnoverPerAdmin"] = np.nan
for i in df_SM.index:
    if (pd.isna(df_SM['TurnoverY0'].loc[i]) == False) and (pd.isna(df_SM['AdminCostsY0'].loc[i]) == False):
        df_SM['TurnoverPerAdmin'].loc[i] = ((df_SM['TurnoverY0'].iloc[i])/(df_SM['AdminCostsY0'].iloc[i]))

In [472]:
df_SM

,Name,TurnoverY0,TurnoverY1,AssetsY0,AssetsY1,AdminCostsY0,AdminCostsY1,Employee#Y0,Employee#Y1,StaffCostsY0,StaffCostsY1,Distribution costsY0,Distribution costsY1,Label,Turnover%change,Turnover/Employee,StaffCostsPerEmployee,TurnoverPerAdmin
0,3D Print N Scan,25496,25496,23894,18408,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0.000000,NaN,NaN,NaN
1,A Edmonds & Co Limited,5585901,6570211,2.3336e+06,2.10878e+06,NaN,NaN,83,87,NaN,NaN,NaN,NaN,1,-14.981406,67300.012048,NaN,NaN
2,A Poole & Son Ltd,5663578,6509953,1.79887e+07,1.68015e+07,1196805,1019332,88,85,3036639,2856370,60200,57308,1,-13.001246,64358.840909,44252.45098,4.732248
3,A.N. Wallis & Co Ltd,26561428,30419178,1.26163e+07,1.1469e+07,4448844,2813988,86,87,3636139,3472915,584429,1669377,1,-12.681967,308853.813953,44252.45098,5.970411
4,AAK (UK) Ltd,255225,262778,33207,38124,8687,8034,430,407,18835,17099,10262,9783,1,-2.874289,593.546512,44252.45098,29.380108
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
793,CF PARTNERS SERVICES (UK) LIMITED,1942281,1714854,1.91999e+06,1.91999e+06,2016775,1565600,6415,48515,1181705,1074602,NaN,NaN,0,13.262179,302.771785,44252.45098,0.963063
794,EUGENE HARRINGTON MARKETING LIMITED,14850692,12880059,4.59729e+06,4.59729e+06,2929212,2538854,188873,142070,1999655,1687352,NaN,NaN,0,15.299876,78.627925,44252.45098,5.069859
795,CRAIG INTERNATIONAL LIMITED,41376742,40797451,4.44909e+06,4.44909e+06,2801468,2889285,NaN,NaN,1818224,1942642,NaN,NaN,0,1.419920,NaN,NaN,14.769664
796,JAMES ALPE LIMITED,10520175,9156383,2.57488e+06,2.57488e+06,1545671,1458455,72539,76813,3474846,3269906,NaN,NaN,0,14.894440,145.027847,44252.45098,6.806219
797,THE HALCYON GALLERY LIMITED,66388756,69026246,1.93987e+07,1.93987e+07,18511763,15000683,757369,766136,8312294,6562001,NaN,NaN,0,-3.820996,87.657081,44252.45098,3.586301

In [473]:
df_SM_PP = df_SM[['Name','TurnoverY0', 'AssetsY0', 'AdminCostsY0','Employee#Y0','StaffCostsY0','Turnover%change','Turnover/Employee','StaffCostsPerEmployee','TurnoverPerAdmin','Label']].copy()
df_SM_PP = df_SM_PP[df_SM_PP['TurnoverY0'].notna()]
df_SM_PP

,Name,TurnoverY0,AssetsY0,AdminCostsY0,Employee#Y0,StaffCostsY0,Turnover%change,Turnover/Employee,StaffCostsPerEmployee,TurnoverPerAdmin,Label
0,3D Print N Scan,25496,23894,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,1
1,A Edmonds & Co Limited,5585901,2.3336e+06,NaN,83,NaN,-14.981406,67300.012048,NaN,NaN,1
2,A Poole & Son Ltd,5663578,1.79887e+07,1196805,88,3036639,-13.001246,64358.840909,44252.45098,4.732248,1
3,A.N. Wallis & Co Ltd,26561428,1.26163e+07,4448844,86,3636139,-12.681967,308853.813953,44252.45098,5.970411,1
4,AAK (UK) Ltd,255225,33207,8687,430,18835,-2.874289,593.546512,44252.45098,29.380108,1
...,...,...,...,...,...,...,...,...,...,...,...
793,CF PARTNERS SERVICES (UK) LIMITED,1942281,1.91999e+06,2016775,6415,1181705,13.262179,302.771785,44252.45098,0.963063,0
794,EUGENE HARRINGTON MARKETING LIMITED,14850692,4.59729e+06,2929212,188873,1999655,15.299876,78.627925,44252.45098,5.069859,0
795,CRAIG INTERNATIONAL LIMITED,41376742,4.44909e+06,2801468,NaN,1818224,1.419920,NaN,NaN,14.769664,0
796,JAMES ALPE LIMITED,10520175,2.57488e+06,1545671,72539,3474846,14.894440,145.027847,44252.45098,6.806219,0
797,THE HALCYON GALLERY LIMITED,66388756,1.93987e+07,18511763,757369,8312294,-3.820996,87.657081,44252.45098,3.586301,0

In [474]:
df_SM_PP.to_csv(r'C:\Users\Clamfighter\Documents\00-Work\Heggle\B2B ML Model\Data\Tritech\SM_Processed.csv',encoding = "ISO-8859-1")

## Averaging Nan Columns

In [475]:
avg_ac = df_SM_PP['AdminCostsY0'].quantile(.5)

for i in df_SM_PP.index:
    if (pd.isna(df_SM_PP['AdminCostsY0'].loc[i]) == True):
        df_SM_PP['AdminCostsY0'].loc[i] = avg_ac

c:\users\clamfighter\machine_learning_project\my_env\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [476]:
avg_ac = df_SM_PP['Employee#Y0'].quantile(.5)

for i in df_SM_PP.index:
    if (pd.isna(df_SM_PP['Employee#Y0'].loc[i]) == True):
        df_SM_PP['Employee#Y0'].loc[i] = avg_ac

In [477]:
avg_ac = df_SM_PP['StaffCostsY0'].quantile(.5)

for i in df_SM_PP.index:
    if (pd.isna(df_SM_PP['StaffCostsY0'].loc[i]) == True):
        df_SM_PP['StaffCostsY0'].loc[i] = avg_ac

In [478]:
avg_ac = df_SM_PP['Turnover%change'].quantile(.5)

for i in df_SM_PP.index:
    if (pd.isna(df_SM_PP['Turnover%change'].loc[i]) == True):
        df_SM_PP['Turnover%change'].loc[i] = avg_ac

In [479]:
avg_ac = df_SM_PP['StaffCostsPerEmployee'].quantile(.5)

for i in df_SM_PP.index:
    if (pd.isna(df_SM_PP['StaffCostsPerEmployee'].loc[i]) == True):
        df_SM_PP['StaffCostsPerEmployee'].loc[i] = avg_ac

In [480]:
avg_ac = df_SM_PP['TurnoverPerAdmin'].quantile(.5)

for i in df_SM.index:
    if (pd.isna(df_SM_PP['TurnoverPerAdmin'].loc[i]) == True):
        df_SM_PP['TurnoverPerAdmin'].loc[i] = avg_ac

In [481]:
avg_ac = df_SM_PP['Turnover/Employee'].quantile(.5)

for i in df_SM.index:
    if (pd.isna(df_SM_PP['Turnover/Employee'].loc[i]) == True):
        df_SM_PP['Turnover/Employee'].loc[i] = avg_ac

In [493]:
avg_ac = df_SM_PP['AssetsY0'].quantile(.5)

for i in df_SM.index:
    if (pd.isna(df_SM_PP['AssetsY0'].loc[i]) == True):
        df_SM_PP['AssetsY0'].loc[i] = avg_ac

c:\users\clamfighter\machine_learning_project\my_env\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [482]:
del df_SM_PP['Name']

In [494]:
df_SM_PP_P = df_SM_PP[df_SM_PP.Label == 1]
df_SM_PP_N = df_SM_PP[df_SM_PP.Label == 0]

In [495]:
df_SM_PP_P = df_SM_PP_P.sample(frac=1)
df_SM_PP_N = df_SM_PP_N.sample(frac=1)

In [496]:
p_train = df_SM_PP_P[:350]
p_test = df_SM_PP_P[350:]
n_train = df_SM_PP_N[:350]
n_test = df_SM_PP_N[350:]

In [497]:
train = pd.concat([p_train,n_train])
test = pd.concat([p_test,n_test])

In [498]:
train = train.sample(frac=1)
test = test.sample(frac=1)

In [499]:
y_train = train['Label']
y_test = test['Label']

In [500]:
x_train = train
x_test = test

In [501]:
del x_train['Label']
del x_test['Label']

In [491]:
y_test

554    0
244    1
492    0
752    0
353    1
      ..
731    0
252    1
145    1
414    0
210    1
Name: Label, Length: 98, dtype: int64

# Training Model

In [505]:
def comfusion_matrix_properties(mat):


    from sklearn.metrics import confusion_matrix

    mat = confusion_matrix(y_test,ypred)
    print("Confusion Matrix:\n\n",mat,"\n")

    TP = mat[0][0]
    FP = mat[0][1]
    FN = mat[1][0]
    TN = mat[1][1]


    # Sensitivity, hit rate, recall, or true positive rate
    TPR = TP/(TP+FN)
    print("True Positive Rate",round(TPR*100,2),"%")

    # Specificity or true negative rate
    TNR = TN/(TN+FP) 
    print("True Negative Rate",round(TNR*100,2),"%")

    # Precision or positive predictive value
    PPV = TP/(TP+FP)
    print("Positive Predictive Value",round(PPV*100,2),"%")

    # Negative predictive value
    NPV = TN/(TN+FN)
    print("Negative Predictive Value",round(NPV*100,2),"%")

    # Fall out or false positive rate
    FPR = FP/(FP+TN)
    print("False Positive Rate",round(FPR*100,2),"%")

    # False negative rate
    FNR = FN/(TP+FN)
    print("False Negative Rate",round(FNR*100,2),"%")

    # False discovery rate
    FDR = FP/(TP+FP)
    print("False Discovery Rate",round(FDR*100,2),"%")


    # Overall accuracy
    ACC = (TP+TN)/(TP+FP+FN+TN)
    print("Overall Accuracy",round(ACC*100,2),"%")

In [502]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(random_state=0)
rfc.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [508]:
ypred = rfc.predict(x_test)

In [509]:
from sklearn.metrics import confusion_matrix

mat = confusion_matrix(y_test,ypred)
print(mat)
comfusion_matrix_properties(mat)

[[48  1]
 [ 2 47]]
Confusion Matrix:

 [[48  1]
 [ 2 47]]

True Positive Rate 96.0 %
True Negative Rate 97.92 %
Positive Predictive Value 97.96 %
Negative Predictive Value 95.92 %
False Positive Rate 2.08 %
False Negative Rate 4.0 %
False Discovery Rate 2.04 %
Overall Accuracy 96.94 %

In [401]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    print(x_train)

      TurnoverY0     AssetsY0 AdminCostsY0 Employee#Y0 StaffCostsY0  \
321     39807000     35945000      6001000         283     12277000
394    101143476     15438778     11479138         433     19661384
763     18108780    4,331,210      8128597      373427      4871143
797      3942890    5,435,827       466979       72988      2240170
609         2684        6,442         1589         265         1642
1        5585901      2333601  2.98262e+06          83  3.39762e+06
455      5751434    5,012,806       743361      233785      2382008
663         2476       44,268       340111        2717       213319
18       1827000       121000      3267000          16  3.39762e+06
244    135800000     97447000  2.98262e+06         757     33935000
650     21205166    3,960,266      5330340      190653      3227573
115     18785257      9060122      4183312          63      2733767
496      1003927      160,442       137885        7670        79135
317      3409000      1595000       750000          27      1071000
311     14921050      7871843      3075840         214      4958958
537     15468643    2,852,482      2333341      274679      3573847
159      1960000      4178000       949000          15       907000
376     16551460      3714679      2278704          90      3422502
610     10891590      859,692      4534496       43062      3129628
80       8008362      2933184      1377703          20      1763741
653     87455291      128,364      6096739        7342      2362733
585     17428762    3,907,774      5056191        3884      3187290
600     11628475      317,480      1744456       91333      1676007
32      99388000     46327000      5306000         412     15168000
527       204665    6,378,272      1895670      129721       926986
170     90707000      3046000     19942000         440     25876000
534     10329365    8,233,057      4268249      100073      2504214
85      10048000      1667000  2.98262e+06          50      1993000
611      6090658   23,265,928      3496509      171555      1585594
65      25458710     15680000      2403001         159      5101453
157     18164550      6811292      1224245          53      2830191
246     22947000     23674000      4608000         143      7334000
339      5377211       237967       471937          20       897209
565      7081651    4,731,949      2651828      392458      1259043
211     25428046      4911879      4391324         154      6277226
393    135746000     44153000  2.98262e+06        1153     70661000
50     212589000    335443000     11018000         996     50072000
578      2245436       83,194      2232099       58213       855679
184     17386000     11063000  2.98262e+06        2717  3.39762e+06
443      1162370          NaN       745080      205606       541150
93      71686073      6795185     14118760         118      7501507
396      8272027      4034697      2789447         100      3639123
690     16074321    3,839,622      3742199      417694      3838073
204     37076000     52034000     14468000         130     13034000
290     22909208     12769221      3799027         194      5269210
94     261973000     18449000     63283000         285     20610000
112     98905000    145380000  2.98262e+06          27     18165000
530     10649344    5,074,679      3876310      339104      2305299
725     25893908          NaN      2092402      298004      1457766
399     16303996   12,842,340      1928116      391460       701362
750      9238041    3,170,686       475115       12000      1763529
795     18022286    2,681,399      2868536      367220      1095773
253    306374000     65282000     10034000         382     21958000
62   67737000000  60676000000    825000000        2717  3.39762e+06
295     13420007       515584      6680708          73      4293353
531     17643305    2,821,559      2325200      214156     11508768
556     11687524      315,559      1978376       26343      1308565
79       8530010       417646      3506805          71      2491644
327     29022842     12418495      4229687         105      7297460
753     16055581          NaN      1554227      342867      1718230
409     13630725    4,718,072      2768208      422354      2238847
655        99036          NaN        37972       11395        25815
787     31182039    1,929,427      4371909      943466      1778205
667      3914176          NaN       874633       68121       907957
268     28299000     10367000      4093000         184      8599000
561      6929339      429,136      1434444       57771      3258292
218     14312000          NaN      1193000        2717  3.39762e+06
15      20089000      7185000      4411000         263  3.39762e+06
277    479319000     85248000      8494000         606     38759000
64       2247531      1756002  2.98262e+06          77      4769217
757      2899246      986,608      1369863        2717       757294
395     43800000     13007000      9191000         124  3.39762e+06
739     53441627   72,144,436      2082445     2950774      6327935
723        35510        6,128          989          86         2679
344     16197423      5254443      5005251          76      2720069
200     29699176     20335295     10573904         274      9318729
122     30965000    128872000     50428000         437        37162
777     20032271    1,562,628       479254      294207       755486
24      18744000     12953000      3975000         188      5509000
660     15213701      406,619      3796903       13775      1303904
121      5811000      1555000  2.98262e+06          15  3.39762e+06
742     84594453   51,085,949     11905708     2364209     34324301
383     53944560      3113699      3752377         293     11838883
770     27270509    4,219,134      5700525      200946      3363840
102     18129142       870870      2614157          61      2200365
195      3964978       569984      1284006          13  3.39762e+06
167     57524398     36229772     10277952         298     15124111
247     26566534      3762970      7687858         114      5259461
107   1344138000    785321000    196123000       21028    317767000
160     44403000     10432000      9697000         227     12464000
473       409363      232,776       323916       43069       198472
31     184145000     25998000      5417000       11026     42306000
502      7645264    3,284,603      1464052       19245      1899146
654       665626          NaN      1061865       71891       702744
303     15191829      6262855      5254957         121      4309575
423    153235357      168,647      2983546       66198     13895161
305    235151000    135346000     66881000         447     20663000
212      2784296      3296764  2.98262e+06          49      1415290
581      7944533    5,438,542      2799480       93007      2936724
178     76289000     75148000     36990000         249     18966000
738     12587266    7,479,203      3580882      500414      2493779
208     17766332      6068211      1095723          48      1301025
386    100548000     51928000     40122000         385     18881000
716     17729102    4,058,630      3254111        9569      3978502
302     18803000     10338000  2.98262e+06         238      8635000
137      6654951      4094214      2267112          62      2375086
201     10010865          NaN      2176016        2717  3.39762e+06
155     52118737     35119631      8743337         116      8125592
66     141344434     41828697     11346426         711     23952586
174    208340000     17015000     18883000        3323     87138000
722     23454934    1,815,357      1402112       11568      1370603
267     10899384      3238938      2996226         120      3202756
553     14787469      471,465       817131      130264     12169359
48      65423144      8143031      5633542         185      9855749
542     16718506    5,877,211       945872      466084      1484746
301     21997233      3406791      7030747         118      3978777
63      36680231     16445632      7595856         237      9366652
767      7955309      784,215     10738993      167744      5431942
214     43091000     23251000  2.98262e+06         159      6500000
136   1520335000   1005395000    107850000        3773    282279000
103      1703000        60000      1468000          26      3658000
627     41324482    4,924,215     10523896       53525      8556521
638     20722219    5,196,962      3059390      138254      3008459
38      92310000    710390000  2.98262e+06        2717    520130000
568      7274804    4,709,229       876584         710      1226644
613     41842043   13,422,727     16618416      307517     11815547
242    559056000    347396000     28878000        2971       126194
104     48416000     54506000      8262000         298     12090000
460     12309508    3,304,654      4496358       50265      2918239
197     84366793     25970769     16195427         732     29038432
669     14622747   16,671,291      2615529      512969      3423229
479     14338304    7,864,380       811274       87450       973761
438     13893527    2,830,182      3383609       37381      2738751
187  33754000000  18357000000  2.98262e+06       99437  3.39762e+06
45     121066796     56120157     96017845         572     73707477
234     16879258      5307342      6194735         143      4172109
781        37795        8,575        18684        3631         7833
665     13594279    6,483,400      5007265      585315      1639181
466     15830550    5,278,840       845041      201438      2704909
108    121168000     30795000     25062000         428     12057000
43      26852000     13460000       684000          77      3992000
693     71871705   15,119,479      2386427      540047      6013746
634      4373986      283,115      1345105       62411       982852
436       540811          NaN       267103        2717       206170
260      8700440      3378662       562158          31  3.39762e+06
186    761623000       299597  2.98262e+06        3699  3.39762e+06
427     16259486   54,020,799      1182232      149078      2659116
58      27550864      4044625      3401209         135      4783993
671     12665858      262,871     12595781       54688      8094906
673     14980451    1,127,717      1538357       97024      5502083
262     75253365     58325582      4160329          91      3172022
299     50009000     14795000     24215000         224     13682000
3       26561428     12616309      4448844          86      3636139
29      50577000     24127000      4491000         140      7074000
577     41940562      422,128      1724797      866181       806027
353    730006000    191997000  2.98262e+06         909     48149000
676      1492648    3,705,654       526207        2717       294531
106    282664000     46805000     29575000         135     39573000
150     17856515      1888491      1348327          34      2397892
118      7354722      3504986      1965025          85      2124398
549      5731885    4,195,494      1679719       66407      2246823
516     12251928    3,966,675      1435984       22623      8734192
526     12679667   19,279,565      8598911       31518      5249020
520        10415      802,145       158473        2717        63743
142      5753694       422548       992617          68      2393176
398       652808       60,895       314399        2717       247818
404     15727017    2,435,460      1351861       76222       756071
715     47141277   16,143,967      7421736     1321614      3544495
717     15601039    1,229,010      2274259       31828      1263638
273    618950000     42855000  2.98262e+06        1623       118000
435     40456341    6,981,115      6469029      270814      4939615
181     16573290      6275876      4739478         153      5852479
662     77201568   51,373,765      5733956      918957      9364344
630      7518958   23,565,520      4955810       10987      2332626
222     10243018      2661140      3959428          38      1762452
381    139319000      8770000      7815000         132      5944000
140     11289244      2699411      1709029          52      2414110
614      5439029          NaN      2888187       68942      2808340
728       255714       97,762       229661       17385       114467
145     31500000    273800000  2.98262e+06        2103     57000000
492     78890090    6,044,791       870870      376510      2177707
12      10571247       822571      3574255          85      3300292
612     28897767    6,131,794      1558899      177277       772127
604      3264562      250,853      3307452      111833      2355832
485     58038508    1,958,028      5399769       62083      3465969
501     19819726    3,387,392      2208967        7029       635664
282     13740061      1514618      1751782          52      3368520
266     25386000    253663000     35509000         522     36522000
322     13041413       229447      2980733          45      2055715
96   12989368000    438190000       153999        2960    576164000
207     12553737      5833254      4897496          96      3882257
369     18273625      6979782      5907153         111      5637633
557      9677511    8,180,102      1583377       46597      3733871
259     41820988     29819799      1219796         172      5159833
251     20417963     19216561      6602908         138      5996930
124   8001000000  31296000000  2.98262e+06        2717   1580000000
46     142069830     12083586     14992149         457     12747370
309    189439000     72010000     36438000         854     49277000
88      60769233      9401369  2.98262e+06         253     11683069
620      1711821      154,796       602385      208867       502976
792     50008059   23,363,486      1635121      495667       216767
478     82005719   75,826,748     24156039     1084836     62213272
175    352724000    182277000     28770000       16377    287039000
727     10647202    4,129,420      1201954        2717      2300017
7       18888645      5916825      3749619         145      5242448
148     20888000        10117      1210000         128      6118000
644     64341733   10,577,414      3389464        2717      1808180
90      26907577      6954959      4180507         231      8311552
367     11846004      2104621      3197991          87      2924370
458     11394323      225,423      2511225       12659      1816739
360    293463000    352883000  2.98262e+06         773     41071000
602     10520175    2,574,884      1545671       72539      3474846
72     362931000    301523000  2.98262e+06        1725     89884000
350     27951000     11130000      5826000         194      8928000
651     30233286    4,526,051       466187      342298      7853731
323   4233000000   2211000000  2.98262e+06       24207   1816000000
729     24546991      512,857      1371749        6143       516731
358     13887000      5663000      2012000         141      6030000
453     16372436    4,614,423      1534573       18116      5861435
586        37080       43,808        51157        2717        45073
151     26441859     12460224      1787569          83      3994767
55      15404757      6391519      2314582         121      4329162
209     55586767     12438287  2.98262e+06         161      6674661
388     77914101     33489798     28975361         679     27740947
227     11352330      2717811      3860857         132      4705252
355  24030000000   5838000000    830000000       97400   2545000000
270      5390412      4962687      3412163          40      2457235
229    142579000     55889000     21851000        1760     80682000
364    692881000    818979000     53487000        2203    268940000
518     11874457    6,590,450      1746901       83424      3053008
768     22034177    2,714,764      2145656       44237      2595123
232  20870000000  21835000000  2.98262e+06       38199   2488000000
735      1074665      335,715       650193       80272       330990
755     23149025    4,960,486      5246116      178682      4582346
240    129133000    112843000     21526000         964     58707000
206     41540000     11604000      4359000         243     10295000
780     28355422    4,627,877      2462466       85244      4456249
425     58618058   15,376,854     36243803      249947      8191840
89     431803000      1620000       278000        2717  3.39762e+06
449      7189079    4,726,645      1479165       43288      2055451
419     32720482   29,899,423     14017866      111946      9853596
706      3056516      315,381       848547        4967       123217
472     21989456    1,486,785       631118       75589      2679611
677     96690740   29,182,884      6535026     1375323      3591120
579     38211111    1,280,618      3729535       13636      2388016
374     11805427      6017409      2344067          70       991802
680     33538360    1,167,411      3240932       42547      1768311
724      1216665      253,653       427973        2717       113598
597      4818333    8,100,715      4711281       46293      2912256
359     35847000      1491000  2.98262e+06         915     26250000
632     15793098    1,385,488      2835127      174983      1680934
779     19879167   14,155,441      1279170       26455       310691
334    289339000     15703000     66445000         434     33437000
331       551415       784860       148323           5       185963
156     19093085       698325      3955294         105      2839055
523     13346120    2,559,451      2165168       36659      1196808
570     22880277          NaN         1000        2850     22864277
793     21845866    4,388,796      3244722       20724      3994849
238     31546000     16440000       956000         171      8213000
625      6999692    5,380,643      3181821      251427      2647918
702     24388014    1,534,173      1246703      827196      1400103
213     11511018        87895      2683585         122      4395124
354    274968000    129231000     33385000        1784     71528000
440     46770476      764,840      1919558       37476      3173018
562      6188415    1,165,943      1489716       65947      2846946
508     34239226    6,851,929      3735464       89082      2901252
220    156930000     39451000     22202000         546     21373000
480       554916      530,397       557758        2717       397778
694     37433001   13,995,984      1659454      354750      6330816
372     36437548     12040898       753450          26       980985
607      7961491   16,988,390       977338       30840       650398
125     14208132      8378287      3061458          52      3088432
721     41368041   20,155,712      6153320       40060      8422754
618     12838648    4,284,546      1463834       23895      4138396
512        85525        5,454        77293        1564        75130
182     22111000     10768000      6317000          70      2626000
190     20237410      4739551      5026323         134      5152865
366   1382600000    798800000    117300000       22864    645800000
692     31154918      585,403      1558034       98647       725379
559     17977682    1,578,761      1059714      250504       822804
756      6962468    5,191,936      2114112       23018      1716598
507     17603606    1,323,497      1745485       63738     10523504
177    825520000    477552000    189195000        2880    204162000
629      4661862    4,769,060       641114      695782      1704008
77       9915041      4021970      2062029          57      1897340
603     14383973      772,233      1633353       40107       616497
183      8763107      5048385       775179          36      1338388
44      12588714      8171459      3016293         168      4524606
243     46572000     12433000     11758000         309      7874000
314     16470153      7460182      5813430         114      7450806
324     28995717     15650726      6086754         285     10152847
35       8136302      1775717      3823104          58      2569905
635      3751681    1,538,257      3985847        2198      2869554

# Running Data Through the Model

In [534]:
df_CD = pd.read_csv(r"C:\Users\Clamfighter\Machine_Learning_Project\my_env\Heggle\B2B Customer Identification\Data\Company_Data_FM.csv",encoding = "ISO-8859-1" ) 
df_CD

,Name,TurnoverY0,TurnoverY1,AssetsY0,AssetsY1,AdminCostsY0,AdminCostsY1,Employee#Y0,Employee#Y1,StaffCostsY0,StaffCostsY1,Distribution costsY0,Distribution costsY1
0,PROTEC FIRE DETECTION PUBLIC LIMITED COMPANY,"84,594,453","80,863,421","51,085,949",NaN,"11,905,708","14,112,354",818.0,820.0,"34,324,301","33,009,245",NaN,NaN
1,JAMESTOWN INDUSTRIES LIMITED,"57,701,332","58,829,973","6,678,122",NaN,"2,276,314","2,167,929",NaN,NaN,"833,156","799,370",NaN,NaN
2,POSTURITE LIMITED,"30,233,286","27,586,035","4,526,051",NaN,"466,187","10,344,027",221.0,220.0,"7,853,731",NaN,NaN,NaN
3,STAR TISSUE UK LIMITED,"29,366,890","24,354,929","5,949,136",NaN,"2,325,430","2,024,896",116.0,94.0,"2,260,497","1,835,398",NaN,NaN
4,BRITISH ELECTRIC LAMPS LIMITED,"23,893,088","21,363,970","9,947,127",NaN,"2,307,629","1,923,147",70.0,67.0,"2,815,937","2,588,811",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,MASSILLY (UK) LIMITED,"7,228","7,385",NaN,NaN,"1,162","1,289",NaN,NaN,NaN,NaN,NaN,NaN
124,Prova Designs Limited,"7,024",NaN,300,NaN,507,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,WOODBRIDGE ENGINEERING (UK) LIMITED,"5,994","7,446",NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN
126,Eclipse Rocketry Ltd,"2,557","16,645",NaN,NaN,"2,078","10,556",2.0,2.0,NaN,NaN,NaN,NaN
127,Motion Custom Works Ltd,"1,902","1,279",NaN,NaN,"1,565","2,532",1.0,1.0,NaN,NaN,NaN,NaN

In [535]:
#If there's no data for y1 turnover, replaces it with y0 turnover
for i in df_CD.index:
    if  pd.isna(df_CD['TurnoverY1'].loc[i]) == True:
        df_CD['TurnoverY1'].loc[i] = df_CD['TurnoverY0'].loc[i]

c:\users\clamfighter\machine_learning_project\my_env\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [536]:
#If there's no data for y1 Assets, replaces it with y0 Assets
count = 0
for i in df_CD.index:
    if (pd.isna(df_CD['AssetsY0'].loc[i]) == False) and (pd.isna(df_CD['AssetsY1'].loc[i]) == True):
        df_CD['AssetsY1'].loc[i] = df_CD['AssetsY0'].loc[i]
        count +=1
print("Number Changed: ",count)

Number Changed:  103

In [537]:
# Removes the ',' from Turnover numbers & converts them into ints
for i in df_CD.index:
    if (pd.isna(df_CD['TurnoverY0'].loc[i]) == False):
        df_CD['TurnoverY0'].loc[i] = str(df_CD['TurnoverY0'].loc[i]).replace(",", "")
        df_CD['TurnoverY1'].loc[i] = str(df_CD['TurnoverY1'].loc[i]).replace(",", "") 
        df_CD['TurnoverY0'].loc[i] = int(df_CD['TurnoverY0'].loc[i])
        df_CD['TurnoverY1'].loc[i] = int(df_CD['TurnoverY1'].loc[i])

In [538]:
# Removes the ',' from Turnover numbers & converts them into ints
for i in df_CD.index: 
    if (pd.isna(df_CD['AssetsY0'].loc[i]) == False):
        df_CD['AssetsY0'].loc[i] = str(df_CD['AssetsY0'].loc[i]).replace(",", "")
        df_CD['AssetsY1'].loc[i] = str(df_CD['AssetsY1'].loc[i]).replace(",", "") 

        df_CD['AssetsY0'].loc[i] = float(df_CD['AssetsY0'].loc[i])
        df_CD['AssetsY1'].loc[i] = float(df_CD['AssetsY1'].loc[i])

In [539]:
#Create new column for % change of turnover, calculates figure and appends the field
df_CD["Turnover%change"] = np.nan
for i in df_CD.index:
    if (pd.isna(df_CD['TurnoverY0'].loc[i]) == False):
        y0 = df_CD['TurnoverY0'].loc[i]
        y1 = df_CD['TurnoverY1'].loc[i]
        
        df_CD['Turnover%change'].loc[i] = (((y0-y1)/y1)*100)

In [540]:
#If there's no data for y1 employees, replaces it with y0 employees
for i in df_CD.index:
    if (pd.isna(df_CD['Employee#Y0'].loc[i]) == False) and (pd.isna(df_CD['Employee#Y1'].loc[i]) == True):
        df_CD['Employee#Y1'].loc[i] = df_CD['Employee#Y0'].loc[i]

In [541]:
# Removes the ',' from Employee numbers & converts them into ints
for i in df_CD.index:
    if (pd.isna(df_CD['Employee#Y0'].loc[i]) == False):
        df_CD['Employee#Y0'].loc[i] = str(df_CD['Employee#Y0'].loc[i]).replace(",", "")
        df_CD['Employee#Y1'].loc[i] = str(df_CD['Employee#Y1'].loc[i]).replace(",", "") 
        df_CD['Employee#Y0'].loc[i] = float(df_CD['Employee#Y0'].loc[i])
        df_CD['Employee#Y1'].loc[i] = float(df_CD['Employee#Y1'].loc[i])

In [542]:
#If there's no data for y1 staffcosts, replaces it with y0 staffcosts
for i in df_CD.index:
    if (pd.isna(df_CD['StaffCostsY0'].loc[i]) == False) and (pd.isna(df_CD['StaffCostsY1'].loc[i]) == True):
        df_CD['StaffCostsY1'].loc[i] = df_CD['StaffCostsY0'].loc[i]

In [543]:
# Removes the ',' from Turnover numbers & converts them into ints
for i in df_CD.index:
    if (pd.isna(df_CD['StaffCostsY0'].loc[i]) == False):
        df_CD['StaffCostsY0'].loc[i] = str(df_CD['StaffCostsY0'].loc[i]).replace(",", "")
        df_CD['StaffCostsY1'].loc[i] = str(df_CD['StaffCostsY1'].loc[i]).replace(",", "") 
        df_CD['StaffCostsY0'].loc[i] = int(df_CD['StaffCostsY0'].loc[i])
        df_CD['StaffCostsY1'].loc[i] = int(df_CD['StaffCostsY1'].loc[i])

In [544]:
#Turnover per employee
#Create new column for % change of turnover, calculates figure and appends the field
df_CD["Turnover/Employee"] = np.nan
for i in df_CD.index:
    if (pd.isna(df_CD['TurnoverY0'].loc[i]) == False) and (pd.isna(df_CD['Employee#Y0'].loc[i]) == False):
        try:
            df_CD['Turnover/Employee'].loc[i] = ((df_CD['TurnoverY0'].iloc[i])/(df_CD['Employee#Y0'].iloc[i]))
        except ZeroDivisionError:
            df_CD['Turnover/Employee'].loc[i] = df_CD['TurnoverY0'].iloc[i]

In [545]:
#Staffcosts per employee
#Create new column for Staffcosts per employee, calculates figure and appends the field
df_CD["StaffCostsPerEmployee"] = np.nan
for i in df_CD.index:
    if (pd.isna(df_CD['StaffCostsY0'].loc[i]) == False) and (pd.isna(df_CD['Employee#Y0'].loc[i]) == False):

        try:
            StaffCostsPerEmployee = ((df_CD['StaffCostsY0'].iloc[i])/(df_CD['Employee#Y0'].iloc[i]))
        except ZeroDivisionError:
            StaffCostsPerEmployee = df_CD['StaffCostsY0'].iloc[i]
        df_CD['StaffCostsPerEmployee'].loc[i] = (TurnoverPerEmployee)

In [546]:
#If there's no data for y1 Admin, replaces it with y0 Admin
for i in df_CD.index:
    if (pd.isna(df_CD['AdminCostsY0'].loc[i]) == False) and (pd.isna(df_CD['AdminCostsY1'].loc[i]) == True):
        df_CD['AdminCostsY1'].loc[i] = df_CD['AdminCostsY0'].loc[i]

In [547]:
# Removes the ',' from Employee numbers & converts them into ints
for i in df_CD.index:
    if (pd.isna(df_CD['AdminCostsY0'].loc[i]) == False):
        df_CD['AdminCostsY0'].loc[i] = str(df_CD['AdminCostsY0'].loc[i]).replace(",", "")
        df_CD['AdminCostsY1'].loc[i] = str(df_CD['AdminCostsY1'].loc[i]).replace(",", "") 
        df_CD['AdminCostsY0'].loc[i] = int(df_CD['AdminCostsY0'].loc[i])
        df_CD['AdminCostsY1'].loc[i] = int(df_CD['AdminCostsY1'].loc[i])

In [548]:
#Turnover per employee
#Create new column for % change of turnover, calculates figure and appends the field
df_CD["TurnoverPerAdmin"] = np.nan
for i in df_CD.index:
    if (pd.isna(df_CD['TurnoverY0'].loc[i]) == False) and (pd.isna(df_CD['AdminCostsY0'].loc[i]) == False):
        df_CD['TurnoverPerAdmin'].loc[i] = ((df_CD['TurnoverY0'].iloc[i])/(df_CD['AdminCostsY0'].iloc[i]))

In [549]:
df_CD

,Name,TurnoverY0,TurnoverY1,AssetsY0,AssetsY1,AdminCostsY0,AdminCostsY1,Employee#Y0,Employee#Y1,StaffCostsY0,StaffCostsY1,Distribution costsY0,Distribution costsY1,Turnover%change,Turnover/Employee,StaffCostsPerEmployee,TurnoverPerAdmin
0,PROTEC FIRE DETECTION PUBLIC LIMITED COMPANY,84594453,80863421,5.10859e+07,5.10859e+07,11905708,14112354,818,820,34324301,33009245,NaN,NaN,4.613992,103416.201711,44252.45098,7.105369
1,JAMESTOWN INDUSTRIES LIMITED,57701332,58829973,6.67812e+06,6.67812e+06,2276314,2167929,NaN,NaN,833156,799370,NaN,NaN,-1.918480,NaN,NaN,25.348582
2,POSTURITE LIMITED,30233286,27586035,4.52605e+06,4.52605e+06,466187,10344027,221,220,7853731,7853731,NaN,NaN,9.596345,136802.199095,44252.45098,64.852272
3,STAR TISSUE UK LIMITED,29366890,24354929,5.94914e+06,5.94914e+06,2325430,2024896,116,94,2260497,1835398,NaN,NaN,20.578836,253162.844828,44252.45098,12.628585
4,BRITISH ELECTRIC LAMPS LIMITED,23893088,21363970,9.94713e+06,9.94713e+06,2307629,1923147,70,67,2815937,2588811,NaN,NaN,11.838240,341329.828571,44252.45098,10.353956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,MASSILLY (UK) LIMITED,7228,7385,NaN,NaN,1162,1289,NaN,NaN,NaN,NaN,NaN,NaN,-2.125931,NaN,NaN,6.220310
124,Prova Designs Limited,7024,7024,300,300,507,507,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,13.854043
125,WOODBRIDGE ENGINEERING (UK) LIMITED,5994,7446,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,-19.500403,5994.000000,NaN,NaN
126,Eclipse Rocketry Ltd,2557,16645,NaN,NaN,2078,10556,2,2,NaN,NaN,NaN,NaN,-84.638029,1278.500000,NaN,1.230510
127,Motion Custom Works Ltd,1902,1279,NaN,NaN,1565,2532,1,1,NaN,NaN,NaN,NaN,48.709930,1902.000000,NaN,1.215335

In [550]:
df_CD_PP = df_CD[['Name','TurnoverY0', 'AssetsY0', 'AdminCostsY0','Employee#Y0','StaffCostsY0','Turnover%change','Turnover/Employee','StaffCostsPerEmployee','TurnoverPerAdmin']].copy()

df_CD_PP

,Name,TurnoverY0,AssetsY0,AdminCostsY0,Employee#Y0,StaffCostsY0,Turnover%change,Turnover/Employee,StaffCostsPerEmployee,TurnoverPerAdmin
0,PROTEC FIRE DETECTION PUBLIC LIMITED COMPANY,84594453,5.10859e+07,11905708,818,34324301,4.613992,103416.201711,44252.45098,7.105369
1,JAMESTOWN INDUSTRIES LIMITED,57701332,6.67812e+06,2276314,NaN,833156,-1.918480,NaN,NaN,25.348582
2,POSTURITE LIMITED,30233286,4.52605e+06,466187,221,7853731,9.596345,136802.199095,44252.45098,64.852272
3,STAR TISSUE UK LIMITED,29366890,5.94914e+06,2325430,116,2260497,20.578836,253162.844828,44252.45098,12.628585
4,BRITISH ELECTRIC LAMPS LIMITED,23893088,9.94713e+06,2307629,70,2815937,11.838240,341329.828571,44252.45098,10.353956
...,...,...,...,...,...,...,...,...,...,...
123,MASSILLY (UK) LIMITED,7228,NaN,1162,NaN,NaN,-2.125931,NaN,NaN,6.220310
124,Prova Designs Limited,7024,300,507,NaN,NaN,0.000000,NaN,NaN,13.854043
125,WOODBRIDGE ENGINEERING (UK) LIMITED,5994,NaN,NaN,1,NaN,-19.500403,5994.000000,NaN,NaN
126,Eclipse Rocketry Ltd,2557,NaN,2078,2,NaN,-84.638029,1278.500000,NaN,1.230510
127,Motion Custom Works Ltd,1902,NaN,1565,1,NaN,48.709930,1902.000000,NaN,1.215335

## AVG Nan Columns

In [551]:
avg_ac = df_CD_PP['AdminCostsY0'].quantile(.5)

for i in df_CD_PP.index:
    if (pd.isna(df_CD_PP['AdminCostsY0'].loc[i]) == True):
        df_CD_PP['AdminCostsY0'].loc[i] = avg_ac

c:\users\clamfighter\machine_learning_project\my_env\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [552]:
avg_ac = df_CD_PP['Employee#Y0'].quantile(.5)

for i in df_CD_PP.index:
    if (pd.isna(df_CD_PP['Employee#Y0'].loc[i]) == True):
        df_CD_PP['Employee#Y0'].loc[i] = avg_ac

In [553]:
avg_ac = df_CD_PP['StaffCostsY0'].quantile(.5)

for i in df_CD_PP.index:
    if (pd.isna(df_CD_PP['StaffCostsY0'].loc[i]) == True):
        df_CD_PP['StaffCostsY0'].loc[i] = avg_ac

In [554]:
avg_ac = df_CD_PP['Turnover%change'].quantile(.5)

for i in df_CD_PP.index:
    if (pd.isna(df_CD_PP['Turnover%change'].loc[i]) == True):
        df_CD_PP['Turnover%change'].loc[i] = avg_ac

In [555]:
avg_ac = df_CD_PP['StaffCostsPerEmployee'].quantile(.5)

for i in df_CD_PP.index:
    if (pd.isna(df_CD_PP['StaffCostsPerEmployee'].loc[i]) == True):
        df_CD_PP['StaffCostsPerEmployee'].loc[i] = avg_ac

In [556]:
avg_ac = df_CD_PP['TurnoverPerAdmin'].quantile(.5)

for i in df_CD_PP.index:
    if (pd.isna(df_CD_PP['TurnoverPerAdmin'].loc[i]) == True):
        df_CD_PP['TurnoverPerAdmin'].loc[i] = avg_ac

In [557]:
avg_ac = df_CD_PP['Turnover/Employee'].quantile(.5)

for i in df_CD_PP.index:
    if (pd.isna(df_CD_PP['Turnover/Employee'].loc[i]) == True):
        df_CD_PP['Turnover/Employee'].loc[i] = avg_ac

In [558]:
avg_ac = df_CD_PP['AssetsY0'].quantile(.5)

for i in df_CD_PP.index:
    if (pd.isna(df_CD_PP['AssetsY0'].loc[i]) == True):
        df_CD_PP['AssetsY0'].loc[i] = avg_ac

In [562]:
names = df_CD_PP['Name']
names

0      PROTEC FIRE DETECTION PUBLIC LIMITED COMPANY
1                      JAMESTOWN INDUSTRIES LIMITED
2                                 POSTURITE LIMITED
3                            STAR TISSUE UK LIMITED
4                    BRITISH ELECTRIC LAMPS LIMITED
                           ...
123                           MASSILLY (UK) LIMITED
124                           Prova Designs Limited
125             WOODBRIDGE ENGINEERING (UK) LIMITED
126                            Eclipse Rocketry Ltd
127                         Motion Custom Works Ltd
Name: Name, Length: 128, dtype: object

In [563]:
del df_CD_PP['Name']

In [564]:
df_CD_PP

,TurnoverY0,AssetsY0,AdminCostsY0,Employee#Y0,StaffCostsY0,Turnover%change,Turnover/Employee,StaffCostsPerEmployee,TurnoverPerAdmin
0,84594453,5.10859e+07,11905708,818,34324301,4.613992,103416.201711,44252.45098,7.105369
1,57701332,6.67812e+06,2276314,32.5,833156,-1.918480,101866.092166,44252.45098,25.348582
2,30233286,4.52605e+06,466187,221,7853731,9.596345,136802.199095,44252.45098,64.852272
3,29366890,5.94914e+06,2325430,116,2260497,20.578836,253162.844828,44252.45098,12.628585
4,23893088,9.94713e+06,2307629,70,2815937,11.838240,341329.828571,44252.45098,10.353956
...,...,...,...,...,...,...,...,...,...
123,7228,575593,1162,32.5,1.86542e+06,-2.125931,101866.092166,44252.45098,6.220310
124,7024,300,507,32.5,1.86542e+06,0.000000,101866.092166,44252.45098,13.854043
125,5994,575593,526207,1,1.86542e+06,-19.500403,5994.000000,44252.45098,3.794430
126,2557,575593,2078,2,1.86542e+06,-84.638029,1278.500000,44252.45098,1.230510
127,1902,575593,1565,1,1.86542e+06,48.709930,1902.000000,44252.45098,1.215335

In [565]:
ypred = rfc.predict(df_CD_PP)

In [566]:
print(ypred)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1
 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 0 1 0 1 1 0 1 1 1
 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 0]

In [567]:
output = df_CD_PP
output['Name'] = names
output['Prediction'] = ypred

In [568]:
output

,TurnoverY0,AssetsY0,AdminCostsY0,Employee#Y0,StaffCostsY0,Turnover%change,Turnover/Employee,StaffCostsPerEmployee,TurnoverPerAdmin,Name,Prediction
0,84594453,5.10859e+07,11905708,818,34324301,4.613992,103416.201711,44252.45098,7.105369,PROTEC FIRE DETECTION PUBLIC LIMITED COMPANY,1
1,57701332,6.67812e+06,2276314,32.5,833156,-1.918480,101866.092166,44252.45098,25.348582,JAMESTOWN INDUSTRIES LIMITED,1
2,30233286,4.52605e+06,466187,221,7853731,9.596345,136802.199095,44252.45098,64.852272,POSTURITE LIMITED,1
3,29366890,5.94914e+06,2325430,116,2260497,20.578836,253162.844828,44252.45098,12.628585,STAR TISSUE UK LIMITED,1
4,23893088,9.94713e+06,2307629,70,2815937,11.838240,341329.828571,44252.45098,10.353956,BRITISH ELECTRIC LAMPS LIMITED,1
...,...,...,...,...,...,...,...,...,...,...,...
123,7228,575593,1162,32.5,1.86542e+06,-2.125931,101866.092166,44252.45098,6.220310,MASSILLY (UK) LIMITED,1
124,7024,300,507,32.5,1.86542e+06,0.000000,101866.092166,44252.45098,13.854043,Prova Designs Limited,1
125,5994,575593,526207,1,1.86542e+06,-19.500403,5994.000000,44252.45098,3.794430,WOODBRIDGE ENGINEERING (UK) LIMITED,0
126,2557,575593,2078,2,1.86542e+06,-84.638029,1278.500000,44252.45098,1.230510,Eclipse Rocketry Ltd,0
127,1902,575593,1565,1,1.86542e+06,48.709930,1902.000000,44252.45098,1.215335,Motion Custom Works Ltd,0

In [569]:
output.to_csv(r'C:\Users\Clamfighter\Documents\00-Work\Heggle\B2B ML Model\Data\Tritech\RF_output.csv',encoding = "ISO-8859-1")